kibana:
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  
  extraEnvs:
  - name: ELASTICSEARCH_USER
    value: kibana_system
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-users-pw
        key: kibana_system
  
  # Security
  kibanaConfig: 
    kibana.yml: |-
      xpack.security.session.idleTimeout: "1h"
      xpack.security.session.lifespan: "30d"
      elasticsearch:
        username: ${ELASTICSEARCH_USER}
        password: ${ELASTICSEARCH_PASSWORD}
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: kibana.eulen.com
        paths:
          - path: /
