apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./resources/namespace-install-ha.yaml 

patchesStrategicMerge:
- ./patches/argocd-cm.yaml
- ./patches/argocd-rbac-cm.yaml

patchesJson6902:
- path: ./patches/argocd-server-insecure-patch.yaml
  target:
    kind: Deployment
    name: argocd-server
